version: '3'

services:
  serv:
    build: .
    container_name: "serv"
    ports:
      - "8000:8000"
    links:
      - postgres:database
  postgres: 
    image: postgres
    environment:
      - POSTGRES_PASSWORD=1
      - POSTGRES_USER=User
      - POSTGRES_DB=Structures
    ports:
      - "5432:5432"